# -*- coding: utf-8 -*-
"""Generate a JianYing assembly script into the user project directory.

The generated business script (kept in the project, per jianying-editor rules)
imports every downloaded segment in order, adds a transition between adjacent
clips, saves the draft, and writes edit/jianying-draft-report.json. It does not
add subtitles or BGM unless the generated script is edited by the user.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

sys.path.insert(0, str(Path(__file__).resolve().parent))
from pipeline_common import (  # noqa: E402
    JY_DRAFTS_ROOT,
    JY_EXE_DEFAULT,
    console,
)


def find_clips(project: Path, batch: str | None, pattern: str) -> list[Path]:
    raw_root = project / "clips" / "raw"
    if batch:
        search_dirs = [raw_root / batch]
    else:
        search_dirs = sorted(
            [p for p in raw_root.iterdir() if p.is_dir()],
            key=lambda p: p.stat().st_mtime,
            reverse=True,
        )
    for directory in search_dirs:
        matches = sorted(directory.glob(pattern), key=lambda p: int(re.search(r"seg_(\d+)_", p.name).group(1)))
        if matches:
            return matches
    return []


ASSEMBLY_TEMPLATE = r'''# -*- coding: utf-8 -*-
"""Assemble generated H3 clips into a JianYing draft (generated by oh-my-minimaxh3-director)."""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path


if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))


def bootstrap_jy() -> None:
    env_root = os.getenv("JY_SKILL_ROOT", "").strip()
    candidates = [
        env_root,
        os.path.join(CURRENT_DIR, ".agent", "skills", "jianying-editor"),
        os.path.join(CURRENT_DIR, ".trae", "skills", "jianying-editor"),
        os.path.join(CURRENT_DIR, ".claude", "skills", "jianying-editor"),
        os.path.join(CURRENT_DIR, "skills", "jianying-editor"),
        r"C:\Users\86150\.agents\skills\jianying-editor",
    ]
    for candidate in candidates:
        if not candidate:
            continue
        scripts_path = os.path.join(os.path.abspath(candidate), "scripts")
        if os.path.exists(os.path.join(scripts_path, "jy_wrapper.py")):
            if scripts_path not in sys.path:
                sys.path.insert(0, scripts_path)
            return
    raise ImportError("Could not find jianying-editor/scripts/jy_wrapper.py")


CLIPS = __CLIPS_JSON__
DRAFT_NAME = __TITLE_JSON__
WIDTH = __WIDTH__
HEIGHT = __HEIGHT__
TRANSITION = __TRANSITION_JSON__
TRANSITION_DURATION = __TRANSITION_DURATION_JSON__
DRAFTS_ROOT = __DRAFTS_ROOT_JSON__
JY_EXE = __JY_EXE_JSON__
REPORT_FILE = Path(CURRENT_DIR) / "edit" / "jianying-draft-report.json"


def main() -> None:
    missing = [clip for clip in CLIPS if not os.path.exists(clip)]
    if missing:
        raise FileNotFoundError("缺少视频片段:\n" + "\n".join(missing))
    if DRAFTS_ROOT:
        os.environ["JY_PROJECTS_ROOT"] = str(DRAFTS_ROOT)
    bootstrap_jy()
    from jy_wrapper import JyProject  # noqa: E402
    from utils.constants import SYNONYMS  # noqa: E402
    from utils.formatters import resolve_enum_with_synonyms  # noqa: E402
    import pyJianYingDraft as draft  # noqa: E402

    project = JyProject(DRAFT_NAME, width=WIDTH, height=HEIGHT, overwrite=True)
    segments = []
    for clip in CLIPS:
        segment = project.add_media_safe(clip)
        if segment is None:
            raise RuntimeError(f"导入失败: {clip}")
        segments.append(segment)
        print("added:", os.path.basename(clip))

    transition_type = resolve_enum_with_synonyms(
        draft.TransitionType, TRANSITION, SYNONYMS
    )
    if transition_type is None:
        print(f"WARN: 无法解析转场 {TRANSITION}，跳过转场")
    else:
        for index in range(len(segments) - 1):
            segments[index].add_transition(transition_type, duration=TRANSITION_DURATION)
            print(f"transition {index + 1}: {TRANSITION} {TRANSITION_DURATION}")

    project.save()
    report = {
        "draft_name": DRAFT_NAME,
        "drafts_root": str(DRAFTS_ROOT) if DRAFTS_ROOT else None,
        "jianying_executable": str(JY_EXE) if JY_EXE else None,
        "canvas": {"width": WIDTH, "height": HEIGHT},
        "video_track": "主视频",
        "video_segments": CLIPS,
        "transition": TRANSITION,
        "transition_duration": TRANSITION_DURATION,
        "subtitle_track": None,
        "background_music": None,
        "saved": True,
    }
    REPORT_FILE.parent.mkdir(parents=True, exist_ok=True)
    REPORT_FILE.write_text(
        json.dumps(report, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    print("DRAFT_SAVED " + json.dumps(report, ensure_ascii=False))


if __name__ == "__main__":
    main()
'''


def build_script(
    clips: list[Path],
    title: str,
    width: int,
    height: int,
    transition: str,
    transition_duration: str,
    drafts_root: Path | None,
    jianying_exe: Path | None,
) -> str:
    def dump(value: object) -> str:
        return json.dumps(value, ensure_ascii=False)

    return (
        ASSEMBLY_TEMPLATE
        .replace("__CLIPS_JSON__", dump([str(c) for c in clips]))
        .replace("__TITLE_JSON__", dump(title))
        .replace("__WIDTH__", str(width))
        .replace("__HEIGHT__", str(height))
        .replace("__TRANSITION_JSON__", dump(transition))
        .replace("__TRANSITION_DURATION_JSON__", dump(transition_duration))
        .replace("__DRAFTS_ROOT_JSON__", dump(str(drafts_root)) if drafts_root else "None")
        .replace("__JY_EXE_JSON__", dump(str(jianying_exe)) if jianying_exe else "None")
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project", type=Path, required=True)
    parser.add_argument("--batch")
    parser.add_argument("--pattern", default="seg_*_00001-audio.mp4")
    parser.add_argument("--title")
    parser.add_argument("--width", type=int, default=1056)
    parser.add_argument("--height", type=int, default=608)
    parser.add_argument("--transition", default="叠化")
    parser.add_argument("--transition-duration", default="0.3s")
    parser.add_argument("--drafts-root", type=Path, default=JY_DRAFTS_ROOT)
    parser.add_argument("--jianying-exe", type=Path, default=JY_EXE_DEFAULT)
    parser.add_argument("--output")
    parser.add_argument("--dry-run", action="store_true", help="只打印脚本不写文件")
    parser.add_argument("--run", action="store_true", help="生成后立即运行")
    args = parser.parse_args()

    project = args.project.resolve()
    clips = find_clips(project, args.batch, args.pattern)
    if not clips:
        raise SystemExit(f"在 {project / 'clips' / 'raw'} 下未找到匹配 {args.pattern} 的片段")
    title = args.title or project.name
    drafts_root = args.drafts_root if args.drafts_root.exists() else None
    jianying_exe = args.jianying_exe if args.jianying_exe.exists() else None
    script = build_script(
        clips, title, args.width, args.height,
        args.transition, args.transition_duration,
        drafts_root, jianying_exe,
    )

    if args.dry_run:
        print(script)
        return 0
    output = Path(args.output) if args.output else project / f"assemble_jianying_{title}.py"
    output.write_text(script, encoding="utf-8", newline="\n")
    console(f"[assembly] 已生成 {output}（{len(clips)} 个片段）")
    if args.run:
        import subprocess
        completed = subprocess.run([sys.executable, "-X", "utf8", str(output)])
        return completed.returncode
    console(f"[assembly] 运行: {sys.executable} -X utf8 {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
